### PR TITLE
Webpack Cleanup

### PR DESCRIPTION
**Pull request by okwolf**
I've done a small refactor to bring the project more in line with others I've working on and seen that use webpack. I've removed the build folder, relocated webpack.config.js to the root (which is the standard location webpack will look, so no need to set that), and moved build/milsymbol.js to src/index.js which is the more standard name for the entry of your webpack bundle. I've also removed the dist folder from git, normally these artifacts are generated as part of the build process and published to places like npm, but only the source files are version controlled.

I know we don't have unit tests yet, so I ran all the examples and it seems to still function as best I can tell. Let me know if you want to only adopt part of this and I will update.

### CODE REVIEW

**Comment by spatialillusions** [comment]
Nice work, I will look into this as soon as possible, at the moment I can't think of anything that should prevent me from merging this.

**Comment by spatialillusions** [comment]
I have had time to look a bit more into your changes now, and I think the restructuring is a good initiative, and I also agree with that the built version of milsymbol shouldn't be version controlled. However, there are some things that would be good that you could help me clarify before I merge this pull.

1. If we put `dist` in the .gitignore won't it be ignored when I publish a release to NPM as well? So can you provide me with an instruction for how I should publish to NPM and get the built version of milsymbol included in the package?

2. This also has to do with the removal of `dist`, because if we don't include it I guess it won't be included in the releases on GitHub, and then bower user won't get access to a working copy of milsymbol, so how can this be solved? I did look into this, https://help.github.com/articles/creating-releases/ , and saw that you can add minified scripts to your release, but I'm not sure how to make sure that they end up in the right folder.

(So I have known that I shouldn't version control the built version but it was an easy solution for me, instead of learning how to do it properly.)

**Comment by okwolf** [comment]
1. See https://docs.npmjs.com/files/package.json#files, the default ignores for npm are only things like .git and node_modules. I'm currently using a similar setup to `npm publish` a few modules.
2. You're correct that GitHub separates source code from distribution artifacts. Is bower the only reason you need to publish the built js to GitHub? I've completely switched away from bower now, and I'm not sure if anyone else used it. There are other options for using the build from npm, such as using the CDN unpkg.com. Please at a look at https://medium.com/@kentcdodds/why-i-don-t-commit-generated-files-to-master-a4d76382564.

At least you already agree on the philosophy of not checking in builds. We just need to work on the mechanics of how 😀

**Comment by spatialillusions** [comment]
It was this part that made me start thinking:
https://docs.npmjs.com/getting-started/publishing-npm-packages#publishing-the-package
"Note that everything in the directory will be included unless it is ignored by a local .gitignore or .npmignore file as described in npm-developers." And in this case we would have a local .gitignore, but I might be wrong here.

It was you who wanted me to keep the bower installation last time I tried to remove it. ;-) The thing here is that it is hard to know if anyone is using it or not, but I did have a user that wanted to install using bower two months ago or so, and this makes that I would like to keep the bower installation for a while.

Also it is simple to point to download the release for people that just wants a built version of milsymbol, otherwise I will have to make some other way to offer the built version and documentation.
So if we just solve the mechanics of all things around this I'm all in for removing the built version.

**Comment by spatialillusions** [comment]
An option here is that we start with reorganizing the code, but keep the dist folder for now and then fix that later. Do you think that would be a good enough solution?

**Comment by okwolf** [comment]
That sounds like a reasonable path forward. I'd rather make progress now than wait a long time for all these issues to get ironed out first. Update pushed.

**Comment by spatialillusions** [comment]
Nice! I see if I can have look into the release procedure.

**Pull request merged**
