### PR TITLE
Mocha Tests

### PR DESCRIPTION
**Pull request by okwolf**
WIP set of unit tests starting from the public-facing API. Most of the calls don't work yet but this puts the plumbing in place to start adding tests.

### CODE REVIEW

**Comment by okwolf** [comment]
`npm test` should give output similar to:

  ms
    API method BBox
      ✓ should be a function
      ✓ should return a Object
    API method ColorMode
      ✓ should be a function
      ✓ should return a Object
    API method addIconParts
      ✓ should be a function
      ✓ should return a Object
    API method addLabelOverrides
      ✓ should be a function
      ✓ should return a Object
    API method addSIDCicons
      ✓ should be a function
      ✓ should return a Object
    API method addSymbolPart
      ✓ should be a function
      ✓ should return a Object
    API method getColorMode
      ✓ should be a function
    API method getDashArrays
      ✓ should be a function
    API method getHqStafLength
      ✓ should be a function
    API method getSymbolParts
      ✓ should be a function
    API method getVersion
      ✓ should be a function
    API method outline
      ✓ should be a function
    API method setColorMode
      ✓ should be a function
    API method setDashArrays
      ✓ should be a function
    API method setHqStafLength
      ✓ should be a function
    API method setStandard
      ✓ should be a function
      ✓ should return a Boolean
    API method setSymbolParts
      ✓ should be a function

  ms.Symbol
    when called with SIDC
      ✓ should return a symbol object
      API method asCanvas
        ✓ should be a function
      API method asDOM
        ✓ should be a function
      API method asSVG
        ✓ should be a function
      API method getAnchor
        ✓ should be a function
      API method getColors
        ✓ should be a function
      API method getOctagonAnchor
        ✓ should be a function
      API method getProperties
        ✓ should be a function
        ✓ should return a Object
      API method getSize
        ✓ should be a function
      API method setOptions
        ✓ should be a function
      API method toDataURL
        ✓ should be a function


  36 passing (25ms)

**Comment by spatialillusions** [comment]
Great work! Could you explain what needs to be fixed to solve this?
`// Most of these don't work yet because of how window/document APIs are used`

asCanvas will be a tricky one to solve, since I don't know of any head less environments to draw canvas, without using things like phantom or similar.

I will have another look after work today and should be able to merge it then.

**Comment by okwolf** [comment]
PhantomJS might be a reasonable stopgap solution but another possible option that I'm currently using in unit tests that rely on the DOM is [jsdom](https://github.com/tmpvar/jsdom). I might give that a go and see if more of the tests pass with it enabled.

**Comment by okwolf** [comment]
So it turns out through a combination of dead-simple mock of window/document/canvas/etc APIs and passing parameters to the methods that require them I have the most basic coverage of the public API of Milsymbol now 😀

**Comment by spatialillusions** [comment]
Nice work! 
I would say that we go for a separate folder for now, if you don't have another opinion. Since you are doing the hard work at the moment you can decide most things, I'm quite open to different solutions. :-) 

If you are able, could you fix the package.json conflict that appeared when the other pull was merged? 
Also do you plan to add some more tests at the moment, or should I merge it as it is? (It is better the more "complete" it is before I do the merge, instead of doing a bunch of small merges.)

**Comment by okwolf** [comment]
Then I'll leave the tests right where they are!

I've resolved the conflict and this should be ready to merge. I think I've gotten the low-hanging fruit, and the next round of tests will be a much bigger effort so I'd like to get this basic level in first.

**Comment by spatialillusions** [comment]
We should mention #57 here so the pull is linked to the issue.

**Comment by okwolf** [comment]
No estimate when the next round of tests will start. Do you think you'll want to participate?

**Comment by spatialillusions** [comment]
Sure I can participate. Since I lack experience of writing unit tests maybe you can make some kind of plan of how we proceed.

**Pull request merged**
